### ISSUE TITLE
Fix warning of leaflet

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/lomap_en2b#108]
When booting the system a warning on leaflet is shown

**Comment by jjgancfer** [comment]
The problem was identified today as part of the function that locates the user, and due to another problem in the tests it has been deleted. The solution will probably be pushed later today or tomorrow, but it should be interesting to add the same feature using the React-Leaflet API; it should be possible and easy to do, but I don't know if we will have time.

**Comment by jjgancfer** [comment]
Fixed in #120.
